import Head from "next/head";

import { CardsRouter } from "../components/cards-router";

import type { NextPage } from "next";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CardsRouter />
      </main>
    </div>
  );
};

export default Home;
