import Head from "next/head";

import { Index } from "../components/pages/index";

import type { NextPage } from "next";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Index />
      </main>
    </div>
  );
};

export default Home;
